from natsrpy._inner.js.kv import KeyValue, KVConfig

class JetStream:
    async def publish(
        self,
        subject: str,
        payload: bytes,
        *,
        headers: dict[str, str] | None = None,
        reply: str | None = None,
        err_on_disconnect: bool = False,
    ) -> None: ...
    async def create_kv(self, config: KVConfig) -> KeyValue: ...
    async def update_kv(self, config: KVConfig) -> KeyValue: ...
    async def get_kv(self, bucket: str) -> KeyValue: ...
    async def delete_kv(self, bucket: str) -> bool: ...
