from natsrpy._inner.js.kv import KeyValue, KVConfig
from natsrpy._inner.js.stream import Stream, StreamConfig

class JetStream:
    async def publish(
        self,
        subject: str,
        payload: bytes,
        *,
        headers: dict[str, str] | None = None,
        reply: str | None = None,
        err_on_disconnect: bool = False,
    ) -> None: ...
    # KV
    async def create_kv(self, config: KVConfig) -> KeyValue: ...
    async def update_kv(self, config: KVConfig) -> KeyValue: ...
    async def get_kv(self, bucket: str) -> KeyValue: ...
    async def delete_kv(self, bucket: str) -> bool: ...
    # Streams
    async def create_stream(self, config: StreamConfig) -> Stream: ...
    async def update_stream(self, config: StreamConfig) -> Stream: ...
    async def get_stream(self, name: str) -> Stream: ...
    async def delete_stream(self, name: str) -> Stream: ...
