from typing import overload

from .consumers import (
    PullConsumer,
    PullConsumerConfig,
    PushConsumer,
    PushConsumerConfig,
)
from .kv import KeyValue, KVConfig
from .stream import Stream, StreamConfig

class StreamsManager:
    async def create(self, config: StreamConfig) -> Stream: ...
    async def create_or_update(self, config: StreamConfig) -> Stream: ...
    async def get(self, bucket: str) -> Stream: ...
    async def delete(self, bucket: str) -> None: ...
    async def update(self, config: StreamConfig) -> Stream: ...

class KVManager:
    async def create(self, config: KVConfig) -> KeyValue: ...
    async def create_or_update(self, config: KVConfig) -> KeyValue: ...
    async def get(self, bucket: str) -> KeyValue: ...
    async def delete(self, bucket: str) -> None: ...
    async def update(self, config: KVConfig) -> KeyValue: ...

class ConsumersManager:
    @overload
    async def create(self, config: PullConsumerConfig) -> PullConsumer: ...
    @overload
    async def create(self, config: PushConsumerConfig) -> PushConsumer: ...
