from datetime import timedelta
from typing import overload

from .consumers import (
    PullConsumer,
    PullConsumerConfig,
    PushConsumer,
    PushConsumerConfig,
)
from .kv import KeyValue, KVConfig
from .object_store import ObjectStore, ObjectStoreConfig
from .stream import Stream, StreamConfig

class StreamsManager:
    async def create(self, config: StreamConfig) -> Stream: ...
    async def create_or_update(self, config: StreamConfig) -> Stream: ...
    async def get(self, bucket: str) -> Stream: ...
    async def delete(self, bucket: str) -> bool: ...
    async def update(self, config: StreamConfig) -> Stream: ...

class KVManager:
    async def create(self, config: KVConfig) -> KeyValue: ...
    async def create_or_update(self, config: KVConfig) -> KeyValue: ...
    async def get(self, bucket: str) -> KeyValue: ...
    async def delete(self, bucket: str) -> bool: ...
    async def update(self, config: KVConfig) -> KeyValue: ...

class ConsumersManager:
    @overload
    async def create(self, config: PullConsumerConfig) -> PullConsumer: ...
    @overload
    async def create(self, config: PushConsumerConfig) -> PushConsumer: ...
    @overload
    async def update(self, config: PullConsumerConfig) -> PullConsumer: ...
    @overload
    async def update(self, config: PushConsumerConfig) -> PushConsumer: ...
    async def get_pull(self, name: str) -> PullConsumer: ...
    async def get_push(self, name: str) -> PushConsumer: ...
    async def delete(self, name: str) -> bool: ...
    async def pause(self, name: str, delay: float | timedelta) -> bool: ...
    async def resume(self, name: str) -> bool: ...

class ObjectStoreManager:
    async def create(self, config: ObjectStoreConfig) -> ObjectStore: ...
    async def get(self, bucket: str) -> ObjectStore: ...
    async def delete(self, bucket: str) -> None: ...
