class NatsrpyBaseError(Exception): ...
class NatsrpySessionError(NatsrpyBaseError): ...
class NatsrpyPublishError(NatsrpyBaseError): ...

__all__ = [
    "NatsrpyBaseError",
    "NatsrpyPublishError",
    "NatsrpySessionError",
]
