from natsrpy._natsrpy_rs.js.kv import KeyValue, KVConfig

class KVManager:
    async def create(self, config: KVConfig) -> KeyValue: ...
    async def create_or_update(self, config: KVConfig) -> KeyValue: ...
    async def get(self, bucket: str) -> KeyValue: ...
    async def delete(self, bucket: str) -> None: ...
    async def update(self, config: KVConfig) -> KeyValue: ...
