from natsrpy._natsrpy_rs.js.stream import Stream, StreamConfig

class StreamsManager:
    async def create(self, config: StreamConfig) -> Stream: ...
    async def create_or_update(self, config: StreamConfig) -> Stream: ...
    async def get(self, bucket: str) -> Stream: ...
    async def delete(self, bucket: str) -> None: ...
    async def update(self, config: StreamConfig) -> Stream: ...
