name: "Testing package"

on:
  pull_request:

jobs:
  py-lint:
    strategy:
      matrix:
        cmd:
          - black
          - ruff
          - mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run lint check
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: -a ${{ matrix.cmd }}
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check code format
        run: cargo fmt -- --check

  clippy:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: auguwu/clippy-action@1.4.0
        with:
            token: ${{secrets.GITHUB_TOKEN}}
            deny: warnings 
