name: "Testing package"

on:
  push:

jobs:
  py-lint:
    strategy:
      matrix:
        cmd:
          - black
          - ruff
          - mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run lint check
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: -a ${{ matrix.cmd }}
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check code format
        run: cargo fmt -- --check

  clippy:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          deny: warnings
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"
          python-version: 3.x
      - id: prepare-container
        name: Prepare docker container
        run: docker compose up -d --wait
      - id: setup-venv
        name: Setup virtualenv
        run: uv venv
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          comand: dev --uv
          sccache: true
      - name: Run pytest
        run: uv run pytest -vv -n auto python/tests
